import { Bass, Kick, Snare, Hihat, Perc } from '@components/Icons';

export const HipHop = [
  {
    src: 'hiphop/21_Perc_1.mp3',
    key: 'q',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'hiphop/22_Perc_2.mp3',
    key: 'w',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'hiphop/23_Perc_3.mp3',
    key: 'e',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'hiphop/24_Perc_4.mp3',
    key: 'r',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'hiphop/12_Hihat_4.mp3',
    key: 'a',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'hiphop/14_Hihat_6.mp3',
    key: 's',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'hiphop/19_Snare_5.mp3',
    key: 'd',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'hiphop/17_Snare_3.mp3',
    key: 'f',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'hiphop/01_808_1.mp3',
    key: 'z',
    name: 'Bass',
    icon: <Bass/>
  }, {
    src: 'hiphop/02_808_2.mp3',
    key: 'x',
    name: 'Bass',
    icon: <Bass/>
  }, {
    src: 'hiphop/05_Kick_3.mp3',
    key: 'c',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'hiphop/06_Kick_4.mp3',
    key: 'v',
    name: 'Kick',
    icon: <Kick/>
  }
];

export const CasioPT30 = [
  {
    src: 'casio-pt-30/pt30-cym2.wav',
    key: 'q',
    name: 'Cymbal',
    icon: <Perc/>
  }, {
    src: 'casio-pt-30/pt30-cym3.wav',
    key: 'w',
    name: 'Cymbal',
    icon: <Perc/>
  }, {
    src: 'casio-pt-30/pt30-per1.wav',
    key: 'e',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'casio-pt-30/pt30-per2.wav',
    key: 'r',
    name: 'Percussion',
    icon: <Perc/>
  }, {
    src: 'casio-pt-30/pt30-hh1.wav',
    key: 'a',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'casio-pt-30/pt30-hh3.wav',
    key: 's',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'casio-pt-30/pt30-sd1.wav',
    key: 'd',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'casio-pt-30/pt30-sd2.wav',
    key: 'f',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'casio-pt-30/pt30-bd1.wav',
    key: 'z',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'casio-pt-30/pt30-bd2.wav',
    key: 'x',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'casio-pt-30/pt30-bd3.wav',
    key: 'c',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'casio-pt-30/pt30-cym1.wav',
    key: 'v',
    name: 'Cymbal',
    icon: <Perc/>
  }
]

export const RealDrums = [
  {
    src: 'pearl-real-kit/pearlkit-ride1.wav',
    key: 'q',
    name: 'Ride',
    icon: <Perc/>
  }, {
    src: 'pearl-real-kit/pearlkit-ride2.wav',
    key: 'w',
    name: 'Ride',
    icon: <Perc/>
  }, {
    src: 'pearl-real-kit/pearlkit-ridebell.wav',
    key: 'e',
    name: 'Ride Bell',
    icon: <Perc/>
  }, {
    src: 'pearl-real-kit/pearlkit-ridecrash.wav',
    key: 'r',
    name: 'Crash',
    icon: <Perc/>
  }, {
    src: 'pearl-real-kit/pearlkit-hihat.wav',
    key: 'a',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'pearl-real-kit/pearlkit-hihatO.wav',
    key: 's',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'pearl-real-kit/pearlkit-snare1.wav',
    key: 'd',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'pearl-real-kit/pearlkit-snare2.wav',
    key: 'f',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'pearl-real-kit/pearlkit-kick.wav',
    key: 'z',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'pearl-real-kit/pearlkit-lowtom1.wav',
    key: 'x',
    name: 'Tom',
    icon: <Kick/>
  }, {
    src: 'pearl-real-kit/pearlkit-lowtom2.wav',
    key: 'c',
    name: 'Tom',
    icon: <Kick/>
  }, {
    src: 'pearl-real-kit/pearlkit-snareroll.wav',
    key: 'v',
    name: 'Snare Roll',
    icon: <Snare/>
  }
]

export const TrapDrums = [
  {
    src: 'urban/urbantrap-percussion-verby-pop.wav',
    key: 'q',
    name: 'Perc',
    icon: <Perc/>
  }, {
    src: 'urban/urbantrap-percussion-tablahit.wav',
    key: 'w',
    name: 'Perc',
    icon: <Perc/>
  }, {
    src: 'urban/urbantrap-percussion-bonk.wav',
    key: 'e',
    name: 'Perc',
    icon: <Perc/>
  }, {
    src: 'urban/urbantrap-percussion-block.wav',
    key: 'r',
    name: 'Perc',
    icon: <Perc/>
  }, {
    src: 'urban/urbantrap-hh-1.wav',
    key: 'a',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'urban/urbantrap-hh-3.wav',
    key: 's',
    name: 'Hi-hat',
    icon: <Hihat/>
  }, {
    src: 'urban/urbantrap-snare-1.wav',
    key: 'd',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'urban/urbantrap-snare-3.wav',
    key: 'f',
    name: 'Snare',
    icon: <Snare/>
  }, {
    src: 'urban/urbantrap-kick-5.wav',
    key: 'z',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'urban/urbantrap-kick-6.wav',
    key: 'x',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'urban/urbantrap-kick-7.wav',
    key: 'c',
    name: 'Kick',
    icon: <Kick/>
  }, {
    src: 'urban/urbantrap-kick-8.wav',
    key: 'v',
    name: 'Kick',
    icon: <Kick/>
  }
]